name: Release

on:
    release:
        types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.23.2

            - name: Install Dependancies
              run: pnpm i

            - name: Publish Package
              run: pnpm publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
